DROP TABLE IF EXISTS completed_appointment CASCADE;
DROP TABLE IF EXISTS medicine CASCADE;
DROP TABLE IF EXISTS physical_examination CASCADE;
DROP TABLE IF EXISTS planned_appointment CASCADE;
DROP TABLE IF EXISTS doctor CASCADE;
DROP TABLE IF EXISTS patient CASCADE;